<?php

namespace App\Seed;

/**
 * Meal ideas offered by the "En manque d'inspi ?" feature (never inserted automatically).
 * Each entry: [name, seasons (empty = all year), product names, optional description].
 * Product names must match ProductCatalog so ideas map onto the household catalogue.
 */
final class MealCatalog
{
    private const ALL = [];
    private const SPRING = ['spring'];
    private const SUMMER = ['summer'];
    private const AUTUMN = ['autumn'];
    private const WINTER = ['winter'];
    private const SPRING_SUMMER = ['spring', 'summer'];
    private const SUMMER_AUTUMN = ['summer', 'autumn'];
    private const AUTUMN_WINTER = ['autumn', 'winter'];

    public const MEALS = [
        // ── Bœuf & viande hachée ──────────────────────────
        ['Lasagnes', self::ALL, ['Viande hachée', 'Feuilles de lasagnes', 'Oignon jaune', 'Coulis de tomate', 'Emmental râpé', 'Lait demi-écrémé', 'Beurre doux', 'Farine de blé'], 'Béchamel maison, 45 min au four à 180 °C.'],
        ['Spaghetti bolognaise', self::ALL, ['Viande hachée', 'Spaghetti', 'Oignon jaune', 'Carotte', 'Coulis de tomate', 'Parmesan']],
        ['Chili con carne', self::AUTUMN_WINTER, ['Viande hachée', 'Haricots rouges en conserve', 'Oignon rouge', 'Poivron rouge', 'Tomates concassées', 'Cumin', 'Riz']],
        ['Hachis parmentier', self::AUTUMN_WINTER, ['Viande hachée', 'Pomme de terre', 'Oignon jaune', 'Lait demi-écrémé', 'Beurre doux', 'Emmental râpé']],
        ['Burgers maison', self::ALL, ['Steak haché', 'Pains burger', 'Cheddar', 'Tomate', 'Salade iceberg', 'Oignon rouge', 'Sauce burger', 'Frites surgelées']],
        ['Tacos', self::ALL, ['Viande hachée', 'Tacos (coques)', 'Tomate', 'Salade iceberg', 'Cheddar', 'Épices tex-mex', 'Crème fraîche épaisse']],
        ['Boulettes à la sauce tomate', self::ALL, ['Viande hachée', 'Œufs', 'Chapelure', 'Sauce tomate', 'Spaghetti', 'Parmesan']],
        ['Moussaka', self::SUMMER_AUTUMN, ['Viande hachée', 'Aubergine', 'Oignon jaune', 'Tomates concassées', 'Lait demi-écrémé', 'Farine de blé', 'Beurre doux', 'Cannelle']],
        ['Cannellonis à la viande', self::AUTUMN_WINTER, ['Cannelloni', 'Viande hachée', 'Coulis de tomate', 'Oignon jaune', 'Emmental râpé']],
        ['Courgettes farcies', self::SUMMER, ['Courgette', 'Chair à saucisse', 'Oignon jaune', 'Riz long', 'Emmental râpé']],
        ['Tomates farcies', self::SUMMER_AUTUMN, ['Tomate', 'Chair à saucisse', 'Oignon jaune', 'Riz long', 'Persil plat']],
        ['Poivrons farcis', self::SUMMER, ['Poivron rouge', 'Viande hachée', 'Riz long', 'Oignon jaune', 'Tomates concassées']],
        ['Steak frites salade', self::ALL, ['Steak', 'Frites surgelées', 'Mâche', 'Moutarde']],
        ['Bœuf bourguignon', self::WINTER, ['Bœuf à braiser', 'Lardons fumés', 'Carotte', 'Oignon jaune', 'Champignons de Paris', 'Vin rouge', 'Bouquet garni', 'Pommes de terre grenailles'], 'Mijoter 3 h, encore meilleur réchauffé.'],
        ['Pot-au-feu', self::WINTER, ['Bœuf pour pot-au-feu', 'Carotte', 'Poireau', 'Navet', 'Pomme de terre', 'Céleri branche', 'Bouquet garni', 'Gros sel']],
        ['Carbonade flamande', self::WINTER, ['Bœuf à braiser', 'Oignon jaune', 'Bière', 'Pain d\'épices', 'Moutarde', 'Frites surgelées']],
        ['Bœuf carottes', self::AUTUMN_WINTER, ['Bœuf à braiser', 'Carotte', 'Oignon jaune', 'Vin blanc', 'Bouquet garni', 'Pomme de terre']],
        ['Daube provençale', self::WINTER, ['Bœuf à braiser', 'Vin rouge', 'Carotte', 'Oignon jaune', 'Olives noires', 'Orange', 'Tagliatelles']],
        ['Entrecôte pommes sautées', self::ALL, ['Entrecôte', 'Pommes de terre sautées', 'Échalote', 'Haricots verts']],
        ['Tartare de bœuf frites', self::SUMMER, ['Bœuf haché pour tartare', 'Câpres', 'Cornichons', 'Échalote', 'Œufs', 'Frites surgelées', 'Moutarde']],
        ['Wok de bœuf aux légumes', self::ALL, ['Émincé de bœuf', 'Wok de légumes', 'Sauce soja', 'Gingembre frais', 'Nouilles chinoises']],
        ['Bœuf Stroganoff', self::AUTUMN_WINTER, ['Émincé de bœuf', 'Champignons de Paris', 'Oignon jaune', 'Crème fraîche épaisse', 'Paprika', 'Riz long']],
        ['Rôti de bœuf haricots verts', self::ALL, ['Rôti de bœuf', 'Haricots verts', 'Pommes de terre grenailles']],
        ['Joues de bœuf confites', self::WINTER, ['Joue de bœuf', 'Vin rouge', 'Carotte', 'Oignon jaune', 'Pomme de terre']],
        ['Brochettes de bœuf', self::SUMMER, ['Brochettes de bœuf', 'Poivron rouge', 'Oignon rouge', 'Pommes de terre grenailles', 'Sauce barbecue']],
        ['Côte de bœuf au barbecue', self::SUMMER, ['Côte de bœuf', 'Pommes de terre grenailles', 'Sauce béarnaise', 'Laitue']],
        ['Enchiladas', self::ALL, ['Tortillas de maïs', 'Viande hachée', 'Haricots rouges en conserve', 'Coulis de tomate', 'Cheddar', 'Épices tex-mex']],
        ['Nachos gratinés', self::ALL, ['Tortilla chips', 'Cheddar', 'Guacamole', 'Viande hachée', 'Tomate', 'Crème fraîche épaisse']],
        ['Keftas et pain pita', self::ALL, ['Viande hachée', 'Cumin', 'Persil plat', 'Oignon jaune', 'Pain pita', 'Yaourt grec']],
        ['Chou farci', self::WINTER, ['Chou vert', 'Chair à saucisse', 'Oignon jaune', 'Carotte', 'Bouillon cube de bœuf']],

        // ── Veau & agneau ─────────────────────────────────
        ['Blanquette de veau', self::AUTUMN_WINTER, ['Veau pour blanquette', 'Carotte', 'Champignons de Paris', 'Oignon blanc', 'Crème fraîche épaisse', 'Riz long', 'Bouillon cube de volaille', 'Citron']],
        ['Escalope milanaise', self::ALL, ['Escalope de veau', 'Œufs', 'Chapelure', 'Farine de blé', 'Spaghetti', 'Sauce tomate', 'Citron']],
        ['Osso buco', self::WINTER, ['Osso buco', 'Tomates concassées', 'Carotte', 'Oignon jaune', 'Vin blanc', 'Citron', 'Tagliatelles']],
        ['Paupiettes de veau', self::AUTUMN_WINTER, ['Paupiette de veau', 'Champignons de Paris', 'Échalote', 'Vin blanc', 'Crème fraîche liquide', 'Riz long']],
        ['Escalope de veau à la normande', self::AUTUMN, ['Escalope de veau', 'Champignons de Paris', 'Crème fraîche épaisse', 'Cidre', 'Tagliatelles']],
        ['Navarin d\'agneau printanier', self::SPRING, ['Agneau pour navarin', 'Carotte', 'Navet', 'Petits pois frais', 'Oignon nouveau', 'Pommes de terre grenailles']],
        ['Gigot d\'agneau aux flageolets', self::SPRING, ['Gigot d\'agneau', 'Flageolets', 'Ail', 'Romarin'], 'Le classique de Pâques.'],
        ['Côtelettes d\'agneau et taboulé', self::SUMMER, ['Côtelettes d\'agneau', 'Semoule', 'Tomate', 'Concombre', 'Menthe', 'Citron']],
        ['Souris d\'agneau confite', self::WINTER, ['Souris d\'agneau', 'Ail', 'Romarin', 'Pommes de terre grenailles', 'Carotte']],
        ['Tajine d\'agneau aux pruneaux', self::WINTER, ['Épaule d\'agneau', 'Pruneaux', 'Amandes', 'Oignon jaune', 'Ras el hanout', 'Semoule']],
        ['Couscous', self::AUTUMN_WINTER, ['Semoule', 'Merguez', 'Cuisse de poulet', 'Légumes pour couscous', 'Pois chiches en conserve', 'Épices à couscous', 'Harissa']],

        // ── Porc & charcuterie ────────────────────────────
        ['Rôti de porc aux lentilles', self::AUTUMN_WINTER, ['Rôti de porc', 'Lentilles vertes', 'Carotte', 'Oignon jaune']],
        ['Filet mignon à la moutarde', self::ALL, ['Filet mignon de porc', 'Moutarde à l\'ancienne', 'Crème fraîche liquide', 'Pommes de terre grenailles']],
        ['Côtes de porc et purée', self::ALL, ['Côte de porc', 'Pomme de terre', 'Lait demi-écrémé', 'Beurre doux']],
        ['Travers de porc caramélisés', self::SUMMER, ['Travers de porc', 'Miel', 'Sauce soja', 'Ail', 'Riz thaï']],
        ['Saucisses aux lentilles', self::AUTUMN_WINTER, ['Saucisse de Morteau', 'Lentilles vertes', 'Carotte', 'Oignon jaune', 'Bouquet garni']],
        ['Saucisses purée', self::ALL, ['Saucisse de Toulouse', 'Pomme de terre', 'Lait demi-écrémé', 'Beurre doux', 'Oignon jaune']],
        ['Rougail saucisse', self::ALL, ['Saucisses fumées', 'Tomate', 'Oignon jaune', 'Gingembre frais', 'Piment frais', 'Riz long']],
        ['Petit salé aux lentilles', self::WINTER, ['Palette de porc', 'Poitrine de porc', 'Lentilles vertes', 'Carotte', 'Oignon jaune', 'Bouquet garni']],
        ['Choucroute garnie', self::WINTER, ['Choucroute', 'Saucisses de Strasbourg', 'Saucisse de Montbéliard', 'Lardons fumés', 'Pomme de terre']],
        ['Cassoulet maison', self::WINTER, ['Haricots blancs', 'Saucisse de Toulouse', 'Confit de canard', 'Poitrine de porc', 'Tomates concassées', 'Oignon jaune', 'Ail']],
        ['Porc au caramel', self::ALL, ['Sauté de porc', 'Sucre en poudre', 'Nuoc-mâm', 'Oignon jaune', 'Riz thaï']],
        ['Échine de porc au barbecue', self::SUMMER, ['Échine de porc', 'Sauce barbecue', 'Épi de maïs', 'Pommes de terre grenailles']],
        ['Andouillette frites', self::ALL, ['Andouillette', 'Moutarde à l\'ancienne', 'Frites surgelées', 'Mâche']],
        ['Boudin noir aux pommes', self::AUTUMN_WINTER, ['Boudin noir', 'Pomme', 'Pomme de terre', 'Beurre doux']],
        ['Potée auvergnate', self::WINTER, ['Chou vert', 'Palette de porc', 'Saucisse de Morteau', 'Carotte', 'Pomme de terre', 'Navet']],
        ['Aligot saucisse', self::WINTER, ['Pomme de terre', 'Tomme', 'Crème fraîche épaisse', 'Ail', 'Saucisse de Toulouse']],
        ['Hot-dogs', self::ALL, ['Pains hot-dog', 'Saucisses de Strasbourg', 'Ketchup', 'Moutarde', 'Oignons frits']],
        ['Jambon purée', self::ALL, ['Jambon blanc', 'Pomme de terre', 'Lait demi-écrémé', 'Beurre doux'], 'Le dépannage préféré des enfants.'],
        ['Endives au jambon', self::WINTER, ['Endive', 'Jambon blanc', 'Lait demi-écrémé', 'Beurre doux', 'Farine de blé', 'Emmental râpé']],
        ['Croque-monsieur salade', self::ALL, ['Pain de mie', 'Jambon blanc', 'Emmental râpé', 'Beurre doux', 'Mâche']],
        ['Coquillettes jambon fromage', self::ALL, ['Coquillettes', 'Jambon blanc', 'Emmental râpé', 'Beurre doux']],
        ['Pâtes carbonara', self::ALL, ['Spaghetti', 'Lardons fumés', 'Œufs', 'Parmesan', 'Poivre noir'], 'La vraie : sans crème !'],
        ['Quiche lorraine', self::ALL, ['Pâte brisée', 'Lardons fumés', 'Œufs', 'Crème fraîche épaisse', 'Lait entier', 'Emmental râpé', 'Mâche']],
        ['Tartiflette', self::WINTER, ['Reblochon', 'Pomme de terre', 'Lardons fumés', 'Oignon jaune', 'Crème fraîche épaisse', 'Vin blanc']],
        ['Raclette', self::WINTER, ['Fromage à raclette', 'Pomme de terre', 'Jambon cru', 'Rosette', 'Jambon blanc', 'Cornichons', 'Salade iceberg']],
        ['Fondue savoyarde', self::WINTER, ['Fromage à fondue', 'Baguette', 'Ail', 'Vin blanc', 'Mâche']],
        ['Mont d\'Or au four', self::WINTER, ['Mont d\'Or', 'Pommes de terre grenailles', 'Jambon cru', 'Vin blanc', 'Cornichons']],
        ['Gratin dauphinois et jambon', self::AUTUMN_WINTER, ['Pomme de terre', 'Crème liquide entière', 'Lait entier', 'Ail', 'Muscade', 'Jambon blanc']],
        ['Galettes complètes', self::ALL, ['Galettes de sarrasin', 'Jambon blanc', 'Emmental râpé', 'Œufs', 'Cidre']],
        ['Crêpes jambon champignons', self::ALL, ['Farine de blé', 'Œufs', 'Lait demi-écrémé', 'Jambon blanc', 'Emmental râpé', 'Champignons de Paris']],
        ['Cake jambon olives', self::ALL, ['Farine de blé', 'Œufs', 'Jambon blanc', 'Olives vertes', 'Gruyère râpé', 'Lait demi-écrémé', 'Levure chimique', 'Mâche']],
        ['Welsh', self::ALL, ['Cheddar', 'Bière', 'Pain de mie', 'Jambon blanc', 'Œufs', 'Frites surgelées']],
        ['Apéro dînatoire', self::ALL, ['Saucisson sec', 'Comté', 'Jambon cru', 'Baguette', 'Cornichons', 'Tomates cerises']],
        ['Pommes de terre en robe des champs', self::AUTUMN_WINTER, ['Pomme de terre', 'Fromage blanc', 'Ciboulette', 'Lardons fumés']],

        // ── Pizzas & tartes ───────────────────────────────
        ['Pizza maison', self::ALL, ['Pâte à pizza', 'Coulis de tomate', 'Mozzarella', 'Jambon blanc', 'Champignons de Paris', 'Origan']],
        ['Pizza 4 fromages', self::ALL, ['Pâte à pizza', 'Mozzarella', 'Gorgonzola', 'Chèvre frais', 'Parmesan', 'Crème fraîche épaisse']],
        ['Pizza chorizo poivrons', self::ALL, ['Pâte à pizza', 'Coulis de tomate', 'Mozzarella râpée', 'Chorizo', 'Poivron rouge', 'Oignon rouge']],
        ['Flammekueche', self::ALL, ['Pâte à pizza', 'Crème fraîche épaisse', 'Fromage blanc', 'Lardons fumés', 'Oignon blanc']],
        ['Tarte poireaux chèvre', self::AUTUMN_WINTER, ['Pâte brisée', 'Poireau', 'Bûche de chèvre', 'Œufs', 'Crème fraîche épaisse']],
        ['Tarte tomate moutarde', self::SUMMER, ['Pâte brisée', 'Tomate', 'Moutarde', 'Emmental râpé', 'Herbes de Provence']],
        ['Tarte fine courgette chèvre', self::SUMMER, ['Pâte feuilletée', 'Courgette', 'Chèvre frais', 'Miel', 'Thym']],
        ['Feuilleté épinards feta', self::ALL, ['Pâte feuilletée', 'Épinards surgelés', 'Feta', 'Œufs']],
        ['Quiche saumon épinards', self::ALL, ['Pâte brisée', 'Saumon fumé', 'Épinards surgelés', 'Œufs', 'Crème fraîche épaisse']],

        // ── Volaille ──────────────────────────────────────
        ['Poulet curry coco', self::ALL, ['Blanc de poulet', 'Lait de coco', 'Curry', 'Oignon jaune', 'Riz basmati', 'Coriandre']],
        ['Poulet rôti pommes de terre', self::ALL, ['Poulet entier', 'Pommes de terre grenailles', 'Ail', 'Thym', 'Huile d\'olive'], '1 h 15 à 200 °C, arroser régulièrement.'],
        ['Poulet basquaise', self::SUMMER_AUTUMN, ['Cuisse de poulet', 'Poivron rouge', 'Poivron vert', 'Tomate', 'Oignon jaune', 'Piment d\'Espelette', 'Riz long']],
        ['Poulet à la crème et aux champignons', self::ALL, ['Blanc de poulet', 'Champignons de Paris', 'Crème fraîche liquide', 'Échalote', 'Tagliatelles']],
        ['Tajine de poulet citron olives', self::ALL, ['Cuisse de poulet', 'Citron', 'Olives vertes', 'Oignon jaune', 'Ras el hanout', 'Semoule']],
        ['Poulet tikka masala', self::ALL, ['Blanc de poulet', 'Yaourt nature', 'Tandoori', 'Tomates concassées', 'Crème fraîche liquide', 'Riz basmati', 'Pain naan']],
        ['Poulet teriyaki', self::ALL, ['Hauts de cuisse de poulet', 'Sauce teriyaki', 'Riz à sushi', 'Graines de sésame', 'Brocoli']],
        ['Fajitas de poulet', self::SUMMER, ['Émincé de poulet', 'Tortillas de blé', 'Poivron rouge', 'Poivron vert', 'Oignon rouge', 'Épices tex-mex', 'Guacamole']],
        ['Quesadillas', self::ALL, ['Tortillas de blé', 'Cheddar', 'Émincé de poulet', 'Poivron rouge', 'Haricots rouges en conserve', 'Guacamole']],
        ['Wraps poulet crudités', self::ALL, ['Tortillas de blé', 'Émincé de poulet', 'Salade iceberg', 'Tomate', 'Sauce blanche']],
        ['Nuggets maison et frites', self::ALL, ['Blanc de poulet', 'Chapelure', 'Œufs', 'Farine de blé', 'Frites surgelées', 'Ketchup']],
        ['Cordon bleu et petits pois', self::ALL, ['Cordon bleu', 'Petits pois carottes'], 'Le repas express des soirs pressés.'],
        ['Poulet yassa', self::ALL, ['Cuisse de poulet', 'Oignon jaune', 'Citron', 'Moutarde', 'Riz long']],
        ['Pilons de poulet au paprika', self::ALL, ['Pilons de poulet', 'Paprika fumé', 'Riz long', 'Poivron rouge']],
        ['Ailes de poulet barbecue', self::SUMMER, ['Ailes de poulet', 'Sauce barbecue', 'Épi de maïs', 'Pommes de terre grenailles']],
        ['Escalopes de dinde à la crème', self::ALL, ['Escalope de dinde', 'Champignons de Paris', 'Crème fraîche liquide', 'Échalote', 'Tagliatelles']],
        ['Rôti de dinde aux marrons', self::WINTER, ['Rôti de dinde', 'Marrons cuits', 'Pommes de terre grenailles']],
        ['Émincé de dinde au curry', self::ALL, ['Émincé de dinde', 'Curry', 'Crème fraîche liquide', 'Oignon jaune', 'Riz basmati']],
        ['Brochettes de poulet et ratatouille', self::SUMMER, ['Brochettes de poulet', 'Courgette', 'Aubergine', 'Poivron rouge', 'Tomate', 'Oignon jaune', 'Herbes de Provence']],
        ['Kebab maison', self::ALL, ['Émincé de poulet', 'Pain pita', 'Tomate', 'Oignon rouge', 'Salade iceberg', 'Sauce blanche', 'Frites surgelées']],
        ['Club sandwich', self::SUMMER, ['Pain de mie', 'Blanc de poulet', 'Bacon', 'Tomate', 'Laitue', 'Mayonnaise', 'Chips']],
        ['Salade César', self::SPRING_SUMMER, ['Romaine', 'Blanc de poulet', 'Parmesan', 'Croûtons', 'Œufs', 'Sauce blanche']],
        ['Magret de canard pommes sarladaises', self::AUTUMN_WINTER, ['Magret de canard', 'Pomme de terre', 'Ail', 'Persil plat']],
        ['Parmentier de canard', self::WINTER, ['Confit de canard', 'Pomme de terre', 'Échalote', 'Lait demi-écrémé', 'Beurre doux']],
        ['Aiguillettes de canard au miel', self::ALL, ['Aiguillettes de canard', 'Miel', 'Vinaigre balsamique', 'Haricots verts']],
        ['Salade landaise', self::ALL, ['Gésiers confits', 'Mesclun', 'Pomme de terre', 'Noix']],
        ['Lapin à la moutarde', self::AUTUMN_WINTER, ['Lapin', 'Moutarde', 'Crème fraîche épaisse', 'Vin blanc', 'Tagliatelles']],
        ['Pintade au chou', self::WINTER, ['Pintade', 'Chou vert', 'Lardons fumés', 'Carotte', 'Oignon jaune']],

        // ── Asie ──────────────────────────────────────────
        ['Pad thaï', self::ALL, ['Nouilles de riz', 'Crevettes crues', 'Œufs', 'Pousses de soja', 'Cacahuètes', 'Citron vert', 'Nuoc-mâm']],
        ['Riz cantonais', self::ALL, ['Riz thaï', 'Œufs', 'Jambon blanc', 'Petits pois surgelés', 'Crevettes cuites', 'Sauce soja']],
        ['Nouilles sautées au poulet', self::ALL, ['Nouilles chinoises', 'Émincé de poulet', 'Wok de légumes', 'Sauce soja', 'Sauce huître']],
        ['Bo bun', self::SUMMER, ['Vermicelles de riz', 'Émincé de bœuf', 'Nems', 'Carotte', 'Concombre', 'Pousses de soja', 'Cacahuètes', 'Menthe', 'Nuoc-mâm']],
        ['Poulet aigre-doux', self::ALL, ['Blanc de poulet', 'Sauce aigre-douce', 'Ananas au sirop', 'Poivron rouge', 'Riz thaï']],
        ['Curry vert de poulet', self::ALL, ['Blanc de poulet', 'Pâte de curry vert', 'Lait de coco', 'Courgette', 'Riz thaï', 'Basilic']],
        ['Soupe de nouilles au poulet', self::AUTUMN_WINTER, ['Nouilles udon', 'Blanc de poulet', 'Bouillon cube de volaille', 'Pak choï', 'Œufs', 'Sauce soja', 'Gingembre frais']],
        ['Poke bowl saumon', self::SUMMER, ['Riz à sushi', 'Pavé de saumon', 'Avocat', 'Concombre', 'Edamame', 'Sauce soja', 'Graines de sésame']],
        ['Wok de crevettes aux nouilles', self::ALL, ['Crevettes crues', 'Nouilles chinoises', 'Wok de légumes', 'Sauce soja', 'Ail']],
        ['Tofu sauté aux légumes', self::ALL, ['Tofu', 'Wok de légumes', 'Sauce soja', 'Riz thaï', 'Graines de sésame']],

        // ── Poissons & fruits de mer ──────────────────────
        ['Pavé de saumon riz brocoli', self::ALL, ['Pavé de saumon', 'Riz basmati', 'Citron', 'Brocoli', 'Aneth']],
        ['Saumon en papillote', self::ALL, ['Pavé de saumon', 'Courgette', 'Citron', 'Aneth', 'Pommes de terre grenailles']],
        ['Cabillaud et purée', self::ALL, ['Dos de cabillaud', 'Pomme de terre', 'Lait demi-écrémé', 'Beurre doux', 'Citron', 'Persil plat']],
        ['Poisson pané haricots verts', self::ALL, ['Poisson pané', 'Haricots verts surgelés', 'Citron', 'Sauce tartare']],
        ['Moules frites', self::SUMMER_AUTUMN, ['Moules', 'Frites surgelées', 'Échalote', 'Vin blanc', 'Persil plat', 'Crème fraîche liquide']],
        ['Crevettes sautées à l\'ail', self::SUMMER, ['Crevettes crues', 'Ail', 'Persil plat', 'Riz thaï', 'Citron vert']],
        ['Paëlla', self::SUMMER, ['Riz long', 'Blanc de poulet', 'Chorizo', 'Crevettes crues', 'Moules', 'Petits pois surgelés', 'Poivron rouge', 'Épices pour paella']],
        ['Tagliatelles au saumon', self::ALL, ['Tagliatelles fraîches', 'Saumon fumé', 'Crème fraîche liquide', 'Aneth', 'Citron']],
        ['Brandade de morue', self::WINTER, ['Brandade de morue', 'Mâche']],
        ['Lieu noir en papillote', self::ALL, ['Lieu noir', 'Tomates cerises', 'Citron', 'Riz long', 'Basilic']],
        ['Dorade au four', self::SUMMER, ['Dorade', 'Citron', 'Fenouil', 'Tomates cerises', 'Huile d\'olive', 'Pommes de terre grenailles']],
        ['Gratin de cabillaud aux épinards', self::AUTUMN_WINTER, ['Filet de cabillaud', 'Épinards surgelés', 'Crème fraîche liquide', 'Emmental râpé', 'Riz long']],
        ['Brochettes de gambas', self::SUMMER, ['Gambas', 'Courgette', 'Citron vert', 'Riz basmati', 'Ail']],
        ['Fish and chips', self::ALL, ['Filet de cabillaud', 'Farine de blé', 'Bière', 'Frites surgelées', 'Sauce tartare']],
        ['Pâtes au thon', self::ALL, ['Penne', 'Thon en conserve', 'Sauce tomate', 'Olives noires', 'Câpres']],
        ['Maquereaux grillés', self::SUMMER, ['Maquereau', 'Citron', 'Pommes de terre grenailles', 'Haricots verts']],
        ['Sardines grillées', self::SUMMER, ['Sardines fraîches', 'Citron', 'Pommes de terre grenailles', 'Laitue']],
        ['Saint-Jacques et fondue de poireaux', self::WINTER, ['Noix de Saint-Jacques', 'Poireau', 'Crème fraîche liquide', 'Riz basmati']],
        ['Calamars à la romaine', self::SUMMER, ['Calamars', 'Farine de blé', 'Œufs', 'Citron', 'Frites surgelées']],
        ['Truite aux amandes', self::ALL, ['Truite', 'Amandes effilées', 'Beurre doux', 'Citron', 'Pommes de terre grenailles']],
        ['Haddock poché aux poireaux', self::WINTER, ['Haddock', 'Lait demi-écrémé', 'Pomme de terre', 'Poireau']],
        ['Raie aux câpres', self::ALL, ['Raie', 'Câpres', 'Beurre doux', 'Pommes de terre grenailles']],
        ['Bricks au thon', self::ALL, ['Feuilles de brick', 'Thon en conserve', 'Œufs', 'Persil plat', 'Citron', 'Laitue']],
        ['Œufs brouillés au saumon fumé', self::ALL, ['Œufs', 'Saumon fumé', 'Pain de campagne', 'Ciboulette']],

        // ── Pâtes, riz & gratins ──────────────────────────
        ['Pâtes au pesto', self::SUMMER, ['Penne', 'Sauce pesto', 'Parmesan', 'Tomates cerises', 'Pignons de pin']],
        ['Risotto aux champignons', self::AUTUMN, ['Riz arborio', 'Champignons de Paris', 'Échalote', 'Vin blanc', 'Parmesan', 'Bouillon cube de volaille', 'Beurre doux']],
        ['Risotto aux asperges', self::SPRING, ['Riz arborio', 'Asperge verte', 'Parmesan', 'Échalote', 'Bouillon cube de légumes', 'Vin blanc']],
        ['Gnocchis à la sauce tomate', self::ALL, ['Gnocchi', 'Sauce tomate', 'Mozzarella', 'Basilic']],
        ['Gnocchis au gorgonzola', self::AUTUMN_WINTER, ['Gnocchi', 'Gorgonzola', 'Crème fraîche liquide', 'Noix']],
        ['Ravioles du Dauphiné gratinées', self::ALL, ['Ravioles du Dauphiné', 'Crème fraîche liquide', 'Emmental râpé', 'Mâche']],
        ['Tortellini crème jambon', self::ALL, ['Tortellini', 'Crème fraîche liquide', 'Jambon blanc', 'Parmesan']],
        ['Pâtes aux 4 fromages', self::ALL, ['Penne', 'Gorgonzola', 'Emmental râpé', 'Parmesan', 'Crème fraîche liquide']],
        ['Spaghetti aglio e olio', self::ALL, ['Spaghetti', 'Ail', 'Piment en flocons', 'Huile d\'olive', 'Persil plat']],
        ['Spaghetti tomate basilic', self::ALL, ['Spaghetti', 'Tomates pelées', 'Ail', 'Basilic', 'Parmesan']],
        ['Macaroni au fromage', self::ALL, ['Macaroni', 'Cheddar', 'Lait demi-écrémé', 'Beurre doux', 'Farine de blé']],
        ['Gratin de pâtes au jambon', self::ALL, ['Macaroni', 'Jambon blanc', 'Crème fraîche liquide', 'Emmental râpé']],
        ['Lasagnes végétariennes', self::ALL, ['Feuilles de lasagnes', 'Courgette', 'Aubergine', 'Ricotta', 'Coulis de tomate', 'Mozzarella']],
        ['Polenta crémeuse aux champignons', self::AUTUMN, ['Polenta', 'Champignons de Paris', 'Parmesan', 'Crème fraîche liquide']],
        ['Salade de riz', self::SUMMER, ['Riz long', 'Thon en conserve', 'Maïs en conserve', 'Tomate', 'Œufs', 'Olives vertes', 'Vinaigrette']],
        ['Salade de pâtes', self::SUMMER, ['Fusilli', 'Tomates cerises', 'Mozzarella', 'Jambon blanc', 'Maïs en conserve', 'Vinaigrette']],

        // ── Végétarien & œufs ─────────────────────────────
        ['Omelette aux champignons', self::ALL, ['Œufs', 'Champignons de Paris', 'Ciboulette', 'Mâche']],
        ['Tortilla espagnole', self::ALL, ['Œufs', 'Pomme de terre', 'Oignon jaune', 'Mâche']],
        ['Œufs cocotte et mouillettes', self::ALL, ['Œufs', 'Crème fraîche épaisse', 'Baguette', 'Jambon blanc']],
        ['Shakshuka', self::ALL, ['Œufs', 'Tomates concassées', 'Poivron rouge', 'Oignon jaune', 'Cumin', 'Pain pita']],
        ['Dahl de lentilles corail', self::AUTUMN_WINTER, ['Lentilles corail', 'Lait de coco', 'Tomates concassées', 'Oignon jaune', 'Curry', 'Gingembre frais', 'Riz basmati']],
        ['Chili sin carne', self::ALL, ['Haricots rouges en conserve', 'Maïs en conserve', 'Poivron rouge', 'Tomates concassées', 'Oignon rouge', 'Cumin', 'Riz']],
        ['Buddha bowl', self::SPRING_SUMMER, ['Quinoa', 'Avocat', 'Pois chiches en conserve', 'Patate douce', 'Jeunes pousses', 'Graines de courge', 'Feta']],
        ['Curry de pois chiches aux épinards', self::ALL, ['Pois chiches en conserve', 'Lait de coco', 'Épinards frais', 'Pâte de curry rouge', 'Riz basmati']],
        ['Falafels et houmous', self::ALL, ['Falafels', 'Houmous', 'Pain pita', 'Tomate', 'Concombre', 'Sauce blanche']],
        ['Burger végétarien', self::ALL, ['Steak végétal', 'Pains burger', 'Tomate', 'Salade iceberg', 'Cheddar', 'Frites surgelées']],
        ['Ratatouille et riz', self::SUMMER, ['Courgette', 'Aubergine', 'Poivron rouge', 'Tomate', 'Oignon jaune', 'Herbes de Provence', 'Riz long']],
        ['Gratin de courgettes', self::SUMMER, ['Courgette', 'Œufs', 'Crème fraîche épaisse', 'Gruyère râpé', 'Riz long']],
        ['Gratin de chou-fleur', self::AUTUMN_WINTER, ['Chou-fleur', 'Lait demi-écrémé', 'Beurre doux', 'Farine de blé', 'Emmental râpé', 'Muscade']],
        ['Galettes de légumes et salade', self::ALL, ['Galettes de légumes', 'Mâche', 'Yaourt grec']],
        ['Salade de chèvre chaud', self::ALL, ['Mesclun', 'Crottin de chèvre', 'Pain de campagne', 'Miel', 'Noix', 'Lardons nature']],
        ['Tartines chèvre miel', self::ALL, ['Pain de campagne', 'Bûche de chèvre', 'Miel', 'Mesclun', 'Noix']],
        ['Bruschettas', self::SUMMER, ['Pain de campagne', 'Tomate', 'Mozzarella', 'Basilic', 'Jambon cru', 'Roquette']],
        ['Salade grecque', self::SUMMER, ['Tomate', 'Concombre', 'Feta', 'Olives noires', 'Oignon rouge', 'Pain pita']],
        ['Melon jambon cru mozzarella', self::SUMMER, ['Melon', 'Jambon cru', 'Mozzarella', 'Roquette']],
        ['Salade niçoise', self::SUMMER, ['Thon en conserve', 'Œufs', 'Tomate', 'Haricots verts', 'Olives noires', 'Pomme de terre', 'Laitue', 'Anchois']],
        ['Taboulé et poulet grillé', self::SUMMER, ['Semoule', 'Tomate', 'Concombre', 'Menthe', 'Persil plat', 'Citron', 'Blanc de poulet']],
        ['Salade de lentilles tiède', self::AUTUMN, ['Lentilles vertes', 'Échalote', 'Œufs', 'Lardons fumés', 'Vinaigrette']],
        ['Gaspacho et tartines', self::SUMMER, ['Gaspacho', 'Pain de campagne', 'Jambon cru', 'Tomates cerises']],
        ['Asperges et œufs mollets', self::SPRING, ['Asperge verte', 'Œufs', 'Parmesan', 'Pain de campagne']],
        ['Asperges blanches sauce hollandaise', self::SPRING, ['Asperge blanche', 'Sauce hollandaise', 'Jambon cru', 'Pommes de terre grenailles']],
        ['Barbecue saucisses merguez', self::SUMMER, ['Chipolatas', 'Merguez', 'Pain de campagne', 'Moutarde', 'Salade de carottes râpées', 'Chips']],

        // ── Soupes ────────────────────────────────────────
        ['Soupe de potiron', self::AUTUMN, ['Potiron', 'Oignon jaune', 'Crème fraîche liquide', 'Bouillon cube de légumes', 'Croûtons']],
        ['Velouté de poireaux pommes de terre', self::AUTUMN_WINTER, ['Poireau', 'Pomme de terre', 'Crème fraîche liquide', 'Bouillon cube de légumes']],
        ['Velouté de butternut coco', self::AUTUMN_WINTER, ['Butternut', 'Oignon jaune', 'Lait de coco', 'Curry', 'Croûtons']],
        ['Soupe de légumes', self::AUTUMN_WINTER, ['Carotte', 'Poireau', 'Pomme de terre', 'Navet', 'Céleri branche', 'Bouillon cube de légumes', 'Pain de campagne']],
        ['Velouté de champignons', self::AUTUMN, ['Champignons de Paris', 'Échalote', 'Crème fraîche liquide', 'Bouillon cube de volaille']],
        ['Soupe à l\'oignon gratinée', self::WINTER, ['Oignon jaune', 'Bouillon cube de bœuf', 'Baguette', 'Gruyère râpé', 'Vin blanc']],
        ['Minestrone', self::AUTUMN_WINTER, ['Haricots blancs', 'Courgette', 'Carotte', 'Céleri branche', 'Tomates concassées', 'Pâtes à soupe', 'Parmesan']],
        ['Velouté de petits pois à la menthe', self::SPRING, ['Petits pois surgelés', 'Menthe', 'Crème fraîche liquide', 'Bouillon cube de légumes']],
    ];
}
